#!/bin/bash

TaskCountFile=$($HOME/bin/get-status-file tasks-count)
RemFile="$PERSONAL_CONFIG_DIR/etc/core.rem"
StateFile="$PERSONAL_CONFIG_DIR/etc/tasks.json"

TasksCountTime=$(stat -c %Y "$TaskCountFile")
RemFileTime=$(stat -c %Y "$RemFile")
StateFileTime=$(stat -c %Y "$StateFile")
NowTime=$(date +%s)

if (($TasksCountTime < $RemFileTime || $TasksCountTime < $StateFileTime || $NowTime - $TasksCountTime > 3600)); then
  python3 "$PERSONAL_CONFIG_DIR/lib/tasks.py" "$RemFile" "$StateFile" due > "$TaskCountFile"
fi

TaskCount="$(cat "$TaskCountFile")"
if (( $TaskCount != 0 )); then
  echo "T: $TaskCount"
else
  python3 "$PERSONAL_CONFIG_DIR/lib/mercury.py"
fi
