let g:is_vim=1

source ~/.ownconfigs/vim/plugins.vim

syn on
set tabstop=2
set shiftwidth=2
set expandtab
set smartindent
set textwidth=80
set hlsearch
set backspace=start,indent
set hidden

set incsearch
set ignorecase
set smartcase
set nocompatible

set wildmode=longest,list
set wildmenu
set formatoptions-=t
set complete-=i

let g:solarized_termcolors=16
let g:solarized_termtrans=1
set background=dark
colorscheme solarized

" Status line settings
set t_Co=256
set laststatus=2
let g:airline_theme='solarized'

