let g:is_vim=1

source ~/.ownconfigs/shared/vim/plugins.vim

syn on
set smartindent
set textwidth=80
set hlsearch
set backspace=start,indent

set incsearch
set ignorecase
set smartcase
set nocompatible

set wildmode=longest,list
set wildmenu
set formatoptions-=t
set complete-=i

source ~/.ownconfigs/shared/vim/shared_post.vim
source ~/.ownconfigs/extras/vimrc
