#!/bin/bash

# Wait for internet to come up
sleep 120

do_check() {
  TmpFile=$(mktemp --tmpdir package-check-XXXXX)
  ResultString="📦"

  checkupdates > "$TmpFile"
  if (( $? != 0 && $? != 2)); then
    echo Error running check updates
    sleep 600
    return 1
  fi

  UpdateCount=$(<"$TmpFile" wc -l)

  if (($UpdateCount == 0)); then
    ResultString="$ResultString ✅"
  else
    ResultString="$ResultString $UpdateCount"
  fi

  ImportantCount=$(<"$TmpFile" grep '^\(linux\) ' | wc -l)
  if (($ImportantCount != 0)); then
    ResultString="$ResultString ❗"
  fi

  echo $ResultString > ~/.ownconfigs/linux/status_files/packages
  echo Update result: $UpdateCount available, $ImportantCount important

  rm $TmpFile
}

while true; do
  PacmanTime=$(stat -c %Y /var/log/pacman.log)
  StatFileTime=$(stat -c %Y ~/.ownconfigs/linux/status_files/packages)
  NowTime=$(date +%s)
  if (($PacmanTime > $StatFileTime || $NowTime - $StatFileTime > 3600)); then
    do_check
  fi
  sleep 15
done
