#!/bin/bash

set -eu

TmpFile=$(mktemp --tmpdir package-check-XXXXX)
ResultString="📦"

# Wait for internet to be ready
checkupdates > "$TmpFile"

UpdateCount=$(<"$TmpFile" wc -l)

if (($UpdateCount == 0)); then
  ResultString="$ResultString ✅"
else
  ResultString="$ResultString $UpdateCount"
fi

ImportantCount=$(<"$TmpFile" grep '^\(linux\) ' | wc -l)
if (($ImportantCount != 0)); then
  ResultString="$ResultString ❗"
fi

echo $ResultString > ~/.ownconfigs/linux/status_files/packages
echo Update result: $UpdateCount available, $ImportantCount important
cat $TmpFile

rm $TmpFile

sleep 300
