#!/bin/bash

Backoff=10

do_check() {
  TmpFile=$(mktemp --tmpdir package-check-XXXXX)
  ResultString="📦"

  checkupdates > "$TmpFile"
  if (( $? != 0 && $? != 2)); then
    echo Error running check updates, waiting $Backoff
    sleep $Backoff
    ((Backoff *= 2))
    if (($Backoff > 300)); then
      Backoff=300
    fi
    return 1
  fi

  UpdateCount=$(<"$TmpFile" wc -l)
  ImportantCount=$(<"$TmpFile" grep '^\(linux\|linux-firmware\|grub\|iptables\) ' | wc -l)

  if (($UpdateCount >= 10)); then
    ResultString="$ResultString $UpdateCount"
  else
    ResultString="$ResultString✅"
  fi

  if (($ImportantCount != 0)); then
    ResultString="$ResultString ❗"
  fi

  echo $ResultString > ~/.ownconfigs/linux/status_files/packages
  date
  echo Update result: $UpdateCount available, $ImportantCount important

  Backoff=10

  rm $TmpFile
}

while true; do
  PacmanTime=$(stat -c %Y /var/log/pacman.log)
  StatFileTime=$(stat -c %Y ~/.ownconfigs/linux/status_files/packages)
  NowTime=$(date +%s)
  if (($PacmanTime > $StatFileTime || $NowTime - $StatFileTime > 3600)); then
    do_check
  fi
  sleep 30
done
