#!/bin/bash

set -e

StatusFile=$($HOME/bin/get-status-file personal-config)

echo "..." > "$StatusFile"

cd "$PERSONAL_CONFIG_DIR/extras/vault"
if [[ -n "$(git status -s)" ]]; then
  git add .
  git commit -m "Sync vault $(date)"
fi

cd "$PERSONAL_CONFIG_DIR"
if [[ -n "$(git status -s)" ]]; then
  echo "" > "$StatusFile"
else
  echo "" > "$StatusFile"
fi
