#!/bin/bash

PackageFile=$($HOME/bin/get-status-file packages)
PackageFileTime=$(stat -c %Y $PackageFile)
PacmanTime=$(stat -c %Y /var/log/pacman.log)
NowTime=$(date +%s)

if (($PacmanTime < $PackageFileTime && $NowTime - $PackageFileTime < 3600)); then
  exit
fi

Backoff=10

TmpFile=$(mktemp --tmpdir package-check-XXXXX)
ResultString="📦"

checkupdates > "$TmpFile"
if (( $? != 0 && $? != 2)); then
  echo Error running check updates
  exit
fi

UpdateCount=$(<"$TmpFile" wc -l)

if (($UpdateCount >= 10)); then
  ResultString="$ResultString $UpdateCount"
else
  ResultString="$ResultString✅"
fi

echo $ResultString > $PackageFile
date
echo Update result: $UpdateCount available

rm $TmpFile

