#!/bin/bash

set -e

StatusFile=$($HOME/bin/get-status-file personal-config)
StatusFileTime=$(stat -c %Y $StatusFile)

cd "$PERSONAL_CONFIG_DIR"
echo "..." > "$StatusFile"

if [[ -n "$(git status -s vault)" ]]; then
  git add vault
  git commit -m "Sync vault $(date)"
  git push
fi

if [[ -n "$(git status -s)" ]]; then
  echo "" > "$StatusFile"
else
  echo "" > "$StatusFile"
fi
