#!/bin/bash

PackageFile=$HOME/.ownconfigs/linux/status_files/packages
PackageFileTime=$(stat -c %Y $PackageFile || echo 0)
EmergeLogTime=$(stat -c %Y /var/log/emerge.log)
PortageTime=$(date -d "$(cat /var/db/repos/gentoo/metadata/timestamp.chk)" +%s)
NowTime=$(date +%s)

ConfigFilesToSync=(
  /etc/genkernel.conf
  /etc/kernels/kernel-config-$(uname -r)
  /etc/portage/make.conf
  /etc/portage/package.use
  /etc/portage/profile/package.provided
  /var/lib/portage/world
)

for f in ${ConfigFilesToSync[@]}; do
  LocalFile=$HOME/.ownconfigs/linux/gentoo/$(basename $f)
  LocalFileTime=$(stat -c %Y $LocalFile)
  LiveConfigTime=$(stat -c %Y $f)
  if (($LiveConfigTime > $LocalFileTime)); then
    cp $f $LocalFile
  fi
done

ChangedFiles=$(git -C $HOME/.ownconfigs status -s | grep linux/gentoo | wc -l)
if (($ChangedFiles != 0)); then
  echo "📦📝" > $PackageFile
  exit
fi

if (($NowTime - $PortageTime > 3600 * 24)); then
  if (($NowTime - $PackageFileTime > 3600)); then
    echo "📦🔄" > ~/.ownconfigs/linux/status_files/packages
  fi
  exit
fi

function check_emerge_update {
  UpdateCount=$(emerge --pretend --quiet --update --deep @world | wc -l)
  if (($UpdateCount >= 5)); then
    echo "📦 $UpdateCount" > $PackageFile
  else
    echo "📦✅" > $PackageFile
  fi
}

if (($PortageTime > $EmergeLogTime && $PackageFileTime - $PortageTime < 600)); then
  check_emerge_update
  exit
fi

if (($EmergeLogTime > $PackageFileTime)); then
  check_emerge_update
  exit
fi

