#!/bin/bash

OtherBranches=$(git branch | grep -v '^*')
declare -a NonDownstreamBranches

for Branch in $OtherBranches; do
  git merge-base --is-ancestor HEAD $Branch || NonDownstreamBranches+=($Branch)
done

git merge-base HEAD ${NonDownstreamBranches[*]}

