#!/bin/bash

set -eu

function countTasks {
  curl -s -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: $LINEAR_API_KEY" \
    --data "$(jq -n --arg query "{
      issues(filter: {
        state: {
          type: { nin: [\"completed\"] }
        }
        dueDate: { lte: \"$1\" }
      }) {
        nodes {
          id
        }
      }
    }" '{"query": $query}')" \
    https://api.linear.app/graphql | jq '.data.issues.nodes | length'
}

TODAY=$(date +%Y-%m-%d)
A=$(countTasks "$TODAY")

[ "$A" -ne 0 ] && echo " $A" && echo "urgent"

exit 0
