#!/bin/bash

Mode="$1"

PrintForLocation() {
  echo "$1 $2"
}

CurrLocation="$(cat "$PERSONAL_CONFIG_DIR/extras/location")"

case "$CurrLocation" in
  Dali)
    PrintForLocation 25.6891429 100.1618383
    ;;
  Qingdao)
    PrintForLocation 36.061938 120.3846191
    ;;
  Shanghai)
    PrintForLocation 31.2325178 121.4734389
    ;;
  "San Francisco")
    PrintForLocation 37.7903826 -122.4000907
    ;;
  Houston)
    PrintForLocation 29.7532704 -95.3596302
    ;;
  Missoula)
    PrintForLocation 46.8721 -113.9940
    ;;
  *)
    echo "Unknown location: $CurrLocation"
    exit 1
esac
