#!/bin/bash

if [ -x "$(command -v multilockscreen)" ]; then
  multilockscreen -l
  multilockscreen -u $PERSONAL_CONFIG_DIR/etc/wallpapers
elif [ -x "$(command -v betterlockscreen)" ]; then
  betterlockscreen -l
  betterlockscreen -u $PERSONAL_CONFIG_DIR/etc/wallpapers
else
  i3lock -c 333333
fi

