#!/bin/bash

if [ -x "$(command -v multilockscreen)" ]; then
  multilockscreen -l
  WallpaperFile=$(ls $PERSONAL_CONFIG_DIR/etc/wallpapers | shuf -n 1)
  multilockscreen -u $PERSONAL_CONFIG_DIR/etc/wallpapers/$WallpaperFile --desc $WallpaperFile --fx ''
elif [ -x "$(command -v betterlockscreen)" ]; then
  betterlockscreen -l
  betterlockscreen -u $PERSONAL_CONFIG_DIR/etc/wallpapers
else
  i3lock -c 333333
fi

