#!/bin/bash

case $1 in
  brightnessup)
    xbacklight -inc 10
    ;;
  brightnessdown)
    xbacklight -dec 10
    ;;
  volup)
    pactl set-sink-volume @DEFAULT_SINK@ +5%
    ;;
  voldown)
    pactl set-sink-volume @DEFAULT_SINK@ -5%
    ;;
  mute)
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    ;;
  mutemic)
    pactl set-source-mute @DEFAULT_SOURCE@ toggle
    ;;
  *)
    echo "UNKNOWN COMMAND"
    exit 1
esac

killall -USR1 py3status || killall -USR1 i3status

