#!/bin/bash

case $1 in
  up)
    pactl set-sink-volume @DEFAULT_SINK@ +5%
    ;;
  down)
    pactl set-sink-volume @DEFAULT_SINK@ -5%
    ;;
  mute)
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    ;;
  mutemic)
    pactl set-source-mute @DEFAULT_SOURCE@ toggle
    ;;
  *)
    echo "UNKNOWN COMMAND"
    exit 1
esac

killall -USR1 i3status

