
font pango:monospace 8

floating_modifier Mod1
focus_wrapping workspace

bindsym Mod1+Return exec kitty
bindsym Mod1+d exec run_command
bindsym Mod1+j exec special-chars
bindsym Mod1+Shift+l exec lock-screen
bindsym --release Mod1+s exec grab-screen

bindsym Mod1+q kill

bindsym XF86MonBrightnessUp exec media-control brightnessup
bindsym XF86MonBrightnessDown exec media-control brightnessdown
bindsym XF86AudioRaiseVolume exec media-control volup
bindsym XF86AudioLowerVolume exec media-control voldown
bindsym XF86AudioMute exec media-control mute
bindsym XF86AudioMicMute exec media-control mutemic

bindsym Mod1+y focus left
bindsym Mod1+n focus down
bindsym Mod1+e focus up
bindsym Mod1+o focus right

bindsym Mod4+y move left
bindsym Mod4+n move down
bindsym Mod4+e move up
bindsym Mod4+o move right

bindsym Mod1+l layout toggle tabbed splith
# bindsym Mod1+t layout tabbed
# bindsym Mod1+e layout toggle split
# bindsym Mod1+v split vertical
# bindsym Mod1+o split horizontal

# toggle tiling / floating
bindsym Mod4+space floating toggle
bindsym Mod1+space focus mode_toggle

# switch to workspace
bindsym Mod1+f workspace 1:
bindsym Mod1+u workspace 2:
bindsym Mod1+p workspace 3:
bindsym Mod1+minus workspace 4:

# move focused container to workspace
bindsym Mod4+f move container to workspace 1:
bindsym Mod4+u move container to workspace 2:
bindsym Mod4+p move container to workspace 3:
bindsym Mod4+minus move container to workspace 4:

bindsym Mod4+backslash move workspace to output right

bindsym Mod1+Shift+q exec "i3-nagbar -t warning -m 'Do you really want to exit i3?' -B 'Yes' 'i3-msg exit'"

bar {
  i3bar_command i3bar -t
  status_command py3status
  strip_workspace_numbers yes
  colors {
    separator #7d7d7d
    background #141414
    statusline #00b0ef
    focused_workspace #00b0ef #141414 #00b0ef #e22395
    active_workspace #141414 #141414 #00b0ef #e22395
    inactive_workspace #141414 #141414 #7d7d7d #7d7d7d
    urgent_workspace #ff7066 #141414 #ff7066 #95b944
  }
}

client.focused #00b0ef #00b0ef #141414 #ff7066
client.focused_inactive #141414 #141414 #00b0ef #472b2a
client.unfocused #141414 #141414 #7d7d7d #141414
client.urgent #ff7066 #ff7066 #141414 #ff7066

hide_edge_borders both
workspace_layout tabbed
